// <auto-generated />
using System;
using GoodStudent.Infrastracture.Postgres.Students;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodStudent.Infrastracture.Postgres.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20251120102527_DropStudents")]
    partial class DropStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodStudent.Infrastracture.Postgres.Students.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profession_id");

                    b.HasKey("Id");

                    b.ToTable("groups");
                });
#pragma warning restore 612, 618
        }
    }
}
