// <auto-generated />
using System;
using GoodStudent.Infrastracture.Postgres.Students;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodStudent.Infrastracture.Postgres.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20251120102013_Checkgroup1")]
    partial class Checkgroup1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodStudent.Infrastracture.Postgres.Students.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profession_id");

                    b.HasKey("Id");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("GoodStudent.Infrastracture.Postgres.Students.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<int>("Student")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<Guid?>("group_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("group_id");

                    b.ToTable("students", t =>
                        {
                            t.Property("group_id")
                                .HasColumnName("group_id1");
                        });
                });

            modelBuilder.Entity("GoodStudent.Infrastracture.Postgres.Students.StudentEntity", b =>
                {
                    b.HasOne("GoodStudent.Infrastracture.Postgres.Students.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("group_id");

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
